### ISSUE TITLE
tests script 

### ISSUE THREAD

**Issue by destruc7i0n** [CodingKanin/PyPixel#10]
Travis will always fail if there is not a test script. Only problem is we need to provide a key to the public :/ 

Maybe remove Travis alltogether?

**Comment by ttofis** [comment]
I got an old account. I can give you that hypixel API key as that account is not used.

**Comment by yrsegal** [comment]
We have keys enough, the problem is putting one out publicly.

**Comment by ttofis** [comment]
I don't care if anyone steals that API key. And we can always create a new one if someone abuses it!

**Comment by ttofis** [comment]
Why do we have to test the hypixel stuff. Let's just test stuff like uuid gets and more. Hypixel API should never change.

**Comment by yrsegal** [comment]
It does, though.

**Comment by ttofis** [comment]
Why... I think let's follow what TheDestruc7i0n said. Let's remove Travis. There are also other services that could do similar jobs to it.

**Comment by destruc7i0n** [comment]
It's not Travis, it's that we need to publicly release a key. I personally like Travis and Circle-CI
