### ISSUE TITLE
Major Update

### ISSUE THREAD

**Issue by destruc7i0n** [CodingKanin/PyPixel#3]
More UUID compatibility 

More functions

**Comment by destruc7i0n** [comment]
I was thinking returning a custom object so that people can send the object in a request and we can get what we need from it. What do you think? Sort of like this https://github.com/Plancke/hypixel-php/blob/master/HypixelPHP.php#L500 @yrsegal

**Comment by yrsegal** [comment]
eeeeh seems a bit convoluted, but I guess it could work

**Comment by destruc7i0n** [comment]
it is a good idea ^^

**Comment by yrsegal** [comment]
you can use Mojang's api to get the username via uuid i guess and vice versa

**Comment by destruc7i0n** [comment]
I can add that function, use http://mcuuid.com/api/ for that

**Comment by destruc7i0n** [comment]
Or do you want to @yrsegal , I hate having an update while you make one too :confused:

**Comment by yrsegal** [comment]
you do it :P

**Comment by destruc7i0n** [comment]
ok

**Comment by destruc7i0n** [comment]
:boom: done

**Comment by destruc7i0n** [comment]
so now, about that custom object... idk how to do that...

**Comment by yrsegal** [comment]
... this is an OOPL, you know... objects aren't that hard to do

**Comment by destruc7i0n** [comment]
I will do something like this then http://stackoverflow.com/questions/3768895/python-how-to-make-a-class-json-serializable

**Comment by yrsegal** [comment]
http://stackoverflow.com/a/15538391

**Comment by yrsegal** [comment]
anyway i'll do the player obj

**Comment by destruc7i0n** [comment]
I will let you do it, I do not have my full amount of resources on this computer with 2GB ram (at school remember?)

**Comment by yrsegal** [comment]
kek, 16gb ram over here

**Comment by destruc7i0n** [comment]
I cannot even edit any code without IE crashing

**Comment by yrsegal** [comment]
IE? xD

**Comment by destruc7i0n** [comment]
yup, no Chrome

**Comment by destruc7i0n** [comment]
When I get home I will work on this more, adding specific objects based on the query, see https://github.com/Plancke/hypixel-php/blob/master/HypixelPHP.php#L1426

**Comment by destruc7i0n** [comment]
Just quickly added some small improvement to the getUUID btw

**Comment by destruc7i0n** [comment]
I am just going to run tests and then this should be closed

**Comment by destruc7i0n** [comment]
When I get home

**Comment by destruc7i0n** [comment]
No need for tests, now to close this!
