### ISSUE TITLE
api.main

### ISSUE THREAD

**Issue by yrsegal** [CodingKanin/PyPixel#4]
```
api.main(str, dict) -> dict
```

api action with name str and options dict, used if an action isn't added yet or you want to hit the Hypixel API server in a specific way

**Comment by destruc7i0n** [comment]
interesting...

**Comment by destruc7i0n** [comment]
you can see many of the functions I want to add here -> https://github.com/Plancke/hypixel-php/blob/master/HypixelPHP.php
