### ISSUE TITLE
Deprecate Usernames

### ISSUE THREAD

**Issue by destruc7i0n** [CodingKanin/PyPixel#5]
Make everything work off of UUID's - the new requirement. `getUUID()` will be used 
**a lot**.

**Comment by destruc7i0n** [comment]
I will make there be options, you can send a dict of options `{"byPlayer":"destruc7i0n"}` would return `getPlayerByUUID("2d8cf844fa3441c38d4e597b32697909")`

**Comment by destruc7i0n** [comment]
Technically all options for using usernames will be automatically routed to the UUID alternative.

**Comment by yrsegal** [comment]
is this done
